// Compiled shader for PC, Mac & Linux Standalone, uncompressed size: 11.5KB

// Skipping shader variants that would not be included into build of current scene.

Shader "Test/Spec_Ref_Shelter_Cutoff" {
Properties {
 _Color ("Color", Color) = (1,1,1,1)
 _MainTex ("MainTex RGB", 2D) = "white" { }
 _BumpMap ("Normal Map", 2D) = "bump" { }
 _SpecIllumBloods ("Spec Illum Bloods", 2D) = "white" { }
 _IllumColor ("Illum Color", Color) = (1,0.00735295,0.00735295,1)
 _MainTex_AlphaRefRange ("(R)Alpha(G)ReflRange(B)Null", 2D) = "white" { }
 _Gloss ("Gloss", Range(0,1)) = 0.5
 _ReflectionCubeMap ("Reflection Cube Map", CUBE) = "_Skybox" { }
 _ReflectionControl ("Reflection Control", Float) = 1
[HideInInspector]  _Cutoff ("Alpha Cutoff", Range(0,1)) = 0.5
 _RimColor ("RimColor", Color) = (0,1,1,1)
 _RimPower ("RimPower", Range(0.1,8)) = 1
}
SubShader { 
 Tags { "QUEUE"="AlphaTest" "RenderType"="TransparentCutout" }


 // Stats for Vertex shader:
 //       d3d11 : 18 math
 //    d3d11_9x : 18 math
 //        d3d9 : 21 math
 // Stats for Fragment shader:
 //        d3d9 : 1 math
 Pass {
  Tags { "QUEUE"="AlphaTest" "RenderType"="TransparentCutout" }
  ZTest Greater
  ZWrite Off
  Blend SrcAlpha One
  GpuProgramID 36898
Program "vp" {
SubProgram "d3d9 " {
// Stats: 21 math
Bind "vertex" Vertex
Bind "normal" Normal
Matrix 4 [_World2Object] 3
Matrix 0 [glstate_matrix_mvp]
Vector 8 [_RimColor]
Float 9 [_RimPower]
Vector 7 [_WorldSpaceCameraPos]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   float4 _RimColor;
//   float _RimPower;
//   row_major float4x4 _World2Object;
//   float3 _WorldSpaceCameraPos;
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   glstate_matrix_mvp   c0       4
//   _World2Object        c4       3
//   _WorldSpaceCameraPos c7       1
//   _RimColor            c8       1
//   _RimPower            c9       1
//

    vs_2_0
    def c10, 1, 0, 0, 0
    dcl_position v0
    dcl_normal v1
    dp4 oPos.x, c0, v0
    dp4 oPos.y, c1, v0
    dp4 oPos.z, c2, v0
    dp4 oPos.w, c3, v0
    mov r0.xy, c10
    mad r0, c7.xyzx, r0.xxxy, r0.yyyx
    dp4 r1.x, c4, r0
    dp4 r1.y, c5, r0
    dp4 r1.z, c6, r0
    add r0.xyz, r1, -v0
    nrm r1.xyz, r0
    dp3 r0.x, r1, v1
    max r0.x, r0.x, c10.y
    min r0.x, r0.x, c10.x
    add r0.x, -r0.x, c10.x
    pow r1.x, r0.x, c9.x
    mul oD0, r1.x, c8

// approximately 21 instruction slots used
"
}
SubProgram "d3d11 " {
// Stats: 18 math
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "$Globals" 128
Vector 96 [_RimColor]
Float 112 [_RimPower]
ConstBuffer "UnityPerCamera" 144
Vector 64 [_WorldSpaceCameraPos] 3
ConstBuffer "UnityPerDraw" 352
Matrix 0 [glstate_matrix_mvp]
Matrix 256 [_World2Object]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityPerDraw" 2
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// COLOR                    0   xyzw        1     NONE   float       
// NORMAL                   0   xyzw        2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer cb0[8], immediateIndexed
      dcl_constantbuffer cb1[5], immediateIndexed
      dcl_constantbuffer cb2[20], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v2.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_temps 1
   0: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
   1: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
   2: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
   3: mad o0.xyzw, cb2[3].xyzw, v0.wwww, r0.xyzw
   4: mul r0.xyz, cb1[4].yyyy, cb2[17].xyzx
   5: mad r0.xyz, cb2[16].xyzx, cb1[4].xxxx, r0.xyzx
   6: mad r0.xyz, cb2[18].xyzx, cb1[4].zzzz, r0.xyzx
   7: add r0.xyz, r0.xyzx, cb2[19].xyzx
   8: add r0.xyz, r0.xyzx, -v0.xyzx
   9: dp3 r0.w, r0.xyzx, r0.xyzx
  10: rsq r0.w, r0.w
  11: mul r0.xyz, r0.wwww, r0.xyzx
  12: dp3_sat r0.x, r0.xyzx, v2.xyzx
  13: add r0.x, -r0.x, l(1.000000)
  14: log r0.x, r0.x
  15: mul r0.x, r0.x, cb0[7].x
  16: exp r0.x, r0.x
  17: mul o1.xyzw, r0.xxxx, cb0[6].xyzw
  18: ret 
// Approximately 0 instruction slots used
"
}
SubProgram "d3d11_9x " {
// Stats: 18 math
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "$Globals" 128
Vector 96 [_RimColor]
Float 112 [_RimPower]
ConstBuffer "UnityPerCamera" 144
Vector 64 [_WorldSpaceCameraPos] 3
ConstBuffer "UnityPerDraw" 352
Matrix 0 [glstate_matrix_mvp]
Matrix 256 [_World2Object]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityPerDraw" 2
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// COLOR                    0   xyzw        1     NONE   float       
// NORMAL                   0   xyzw        2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Constant buffer to DX9 shader constant mappings:
//
// Target Reg Buffer  Start Reg # of Regs        Data Conversion
// ---------- ------- --------- --------- ----------------------
// c1         cb0             6         2  ( FLT, FLT, FLT, FLT)
// c3         cb1             4         1  ( FLT, FLT, FLT, FLT)
// c4         cb2             0         4  ( FLT, FLT, FLT, FLT)
// c8         cb2            16         4  ( FLT, FLT, FLT, FLT)
//
//
// Runtime generated constant mappings:
//
// Target Reg                               Constant Description
// ---------- --------------------------------------------------
// c0                              Vertex Shader position offset
//
//
// Level9 shader bytecode:
//
    vs_2_0
          def c12, 0, 1, 0, 0
          dcl_texcoord v0
          dcl_texcoord2 v2
   0:     mov r0.xyz, c3
   1:     mul r1.xyz, r0.y, c9
   2:     mad r0.xyw, c8.xyzz, r0.x, r1.xyzz
   3:     mad r0.xyz, c10, r0.z, r0.xyww
   4:     add r0.xyz, r0, c11
   5:     add r0.xyz, r0, -v0
   6:     nrm r1.xyz, r0
   9:     dp3 r0.x, r1, v2
  10:     max r0.x, r0.x, c12.x
  11:     min r0.x, r0.x, c12.y
  12:     add r0.x, -r0.x, c12.y
  13:     pow r1.x, r0.x, c2.x
  16:     mul oT0, r1.x, c1
  17:     mul r0, v0.y, c5
  18:     mad r0, c4, v0.x, r0
  19:     mad r0, c6, v0.z, r0
  20:     mad r0, c7, v0.w, r0
  21:     mad oPos.xy, r0.w, c0, r0
  22:     mov oPos.zw, r0

// approximately 23 instruction slots used
      vs_4_0
      dcl_constantbuffer cb0[8], immediateIndexed
      dcl_constantbuffer cb1[5], immediateIndexed
      dcl_constantbuffer cb2[20], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v2.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_temps 1
   0: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
   1: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
   2: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
   3: mad o0.xyzw, cb2[3].xyzw, v0.wwww, r0.xyzw
   4: mul r0.xyz, cb1[4].yyyy, cb2[17].xyzx
   5: mad r0.xyz, cb2[16].xyzx, cb1[4].xxxx, r0.xyzx
   6: mad r0.xyz, cb2[18].xyzx, cb1[4].zzzz, r0.xyzx
   7: add r0.xyz, r0.xyzx, cb2[19].xyzx
   8: add r0.xyz, r0.xyzx, -v0.xyzx
   9: dp3 r0.w, r0.xyzx, r0.xyzx
  10: rsq r0.w, r0.w
  11: mul r0.xyz, r0.wwww, r0.xyzx
  12: dp3_sat r0.x, r0.xyzx, v2.xyzx
  13: add r0.x, -r0.x, l(1.000000)
  14: log r0.x, r0.x
  15: mul r0.x, r0.x, cb0[7].x
  16: exp r0.x, r0.x
  17: mul o1.xyzw, r0.xxxx, cb0[6].xyzw
  18: ret 
// Approximately 0 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 1 math
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
    ps_2_0
    dcl v0
    mov_pp oC0, v0

// approximately 1 instruction slot used
"
}
SubProgram "d3d11 " {
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_input_ps linear v1.xyzw
      dcl_output o0.xyzw
   0: mov o0.xyzw, v1.xyzw
   1: ret 
// Approximately 0 instruction slots used
"
}
SubProgram "d3d11_9x " {
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
//
// Level9 shader bytecode:
//
    ps_2_0
          dcl_pp t0
   0:     mov_pp oC0, t0

// approximately 1 instruction slot used
      ps_4_0
      dcl_input_ps linear v1.xyzw
      dcl_output o0.xyzw
   0: mov o0.xyzw, v1.xyzw
   1: ret 
// Approximately 0 instruction slots used
"
}
}
 }
 Pass {
  Name "FORWARD"
  Tags { "LIGHTMODE"="ForwardBase" "QUEUE"="AlphaTest" "SHADOWSUPPORT"="true" "RenderType"="TransparentCutout" }
  GpuProgramID 123634
Program "vp" {
// Platform d3d9 had shader errors
//   Keywords { "DIRECTIONAL" "SHADOWS_OFF" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
//   Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
//   Keywords { "DIRECTIONAL" "SHADOWS_OFF" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" "VERTEXLIGHT_ON" }
//   Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" "VERTEXLIGHT_ON" }
// Platform d3d11 had shader errors
//   Keywords { "DIRECTIONAL" "SHADOWS_OFF" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
//   Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
//   Keywords { "DIRECTIONAL" "SHADOWS_OFF" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" "VERTEXLIGHT_ON" }
//   Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" "VERTEXLIGHT_ON" }
}
Program "fp" {
// Platform d3d9 had shader errors
//   Keywords { "DIRECTIONAL" "SHADOWS_OFF" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
//   Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
// Platform d3d11 had shader errors
//   Keywords { "DIRECTIONAL" "SHADOWS_OFF" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
//   Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "DYNAMICLIGHTMAP_OFF" }
}
 }
}
Fallback "Diffuse"
}